backend:
    name: github
    repo: kevinshu1995/photography-gallery
    base_url: https://photograph-oauth.hsiu.soy

site_url: https://photograph.hsiu.soy

media_folder: public/img
public_folder: /img

collections:
    - name: "gallery"
      label: "相簿管理"
      folder: "content/gallery"
      extension: "json"
      format: "json"
      identifier_field: "filename"
      fields:
          - { label: "圖片路徑", name: "image", widget: "image", media_folder: "/public/img", allow_multiple: false, readonly: true }
          - { label: "描述", name: "description", widget: "text", required: false }
          - { label: "拍攝日期", name: "date", widget: "datetime", required: false }
          - { label: "標籤", name: "tags", widget: "list", allow_add: true, allow_remove: true, required: false }
          - { label: "位置", name: "location", widget: "string", required: false }
          - { label: "發佈", name: "published", widget: "boolean", default: true, required: true }
          - { label: "權重", name: "weight", widget: "number", value_type: "int", required: false, default: 0 }

